# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'portConfig.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(178, 191)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbox_port = QtWidgets.QComboBox(Dialog)
        self.cbox_port.setObjectName("cbox_port")
        self.verticalLayout.addWidget(self.cbox_port)
        self.cbox_baudrate = QtWidgets.QComboBox(Dialog)
        self.cbox_baudrate.setObjectName("cbox_baudrate")
        self.verticalLayout.addWidget(self.cbox_baudrate)
        self.cbox_databit = QtWidgets.QComboBox(Dialog)
        self.cbox_databit.setObjectName("cbox_databit")
        self.verticalLayout.addWidget(self.cbox_databit)
        self.cbox_paritybit = QtWidgets.QComboBox(Dialog)
        self.cbox_paritybit.setObjectName("cbox_paritybit")
        self.verticalLayout.addWidget(self.cbox_paritybit)
        self.cbox_stopbit = QtWidgets.QComboBox(Dialog)
        self.cbox_stopbit.setObjectName("cbox_stopbit")
        self.verticalLayout.addWidget(self.cbox_stopbit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 6)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_portconfig_Open = QtWidgets.QPushButton(Dialog)
        self.btn_portconfig_Open.setObjectName("btn_portconfig_Open")
        self.horizontalLayout_2.addWidget(self.btn_portconfig_Open)
        self.btn_portconfig_Cancel = QtWidgets.QPushButton(Dialog)
        self.btn_portconfig_Cancel.setObjectName("btn_portconfig_Cancel")
        self.horizontalLayout_2.addWidget(self.btn_portconfig_Cancel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.btn_portconfig_Open.clicked.connect(Dialog.accept)
        self.btn_portconfig_Cancel.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "配置端口"))
        self.label.setText(_translate("Dialog", "端口号："))
        self.label_2.setText(_translate("Dialog", "波特率："))
        self.label_3.setText(_translate("Dialog", "数据位："))
        self.label_4.setText(_translate("Dialog", "校验位："))
        self.label_5.setText(_translate("Dialog", "停止位："))
        self.btn_portconfig_Open.setText(_translate("Dialog", "确定"))
        self.btn_portconfig_Cancel.setText(_translate("Dialog", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
